### ISSUE TITLE
Why not using UIDynamics Kit ? 

### ISSUE THREAD

**Issue by Akhu** [nathangitter/fluid-interfaces#6]
Hi ! 

Very nice work here, Thanks for sharing :)

I was just asking myself why there is no uses the UIDynamics Kit from Apple, that could help achieve almost all of theses interactions without struggling with long and complexe animations code.

Is this on purpose ? For performance reason or something? I feel I am missing something because I nearly never see iOS developer use this framework.

So if someone can helps me on this I would very appreciate the explanation.

Thanks !

**Comment by nathangitter** [comment]
Hi Akhu,

[UIKit Dynamics](https://developer.apple.com/documentation/uikit/animation_and_haptics/uikit_dynamics) is a powerful part of the UIKit framework. I've mainly used it for animations that simulate physics, although it might be possible to create some of these animations with it.

I would actually be very interested in seeing some of these interfaces built with UIKit Dynamics, especially if it does reduce the complexity as you claim.

Have you built any similar animations with UIKit Dynamics? Or would you be willing to try building one of these interfaces using it? It would be really cool to see a side-by-side comparison of the code, especially if they can reach feature parity.

**Comment by Akhu** [comment]
Okay, 

I will make them from your repo, you have a great code base here :) 
Making a fork and overriding some animations will do the trick, for science 👍 

Thanks for your reply.
